# Generated by Django 5.1 on 2024-09-02 16:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "cve_producto",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("descripcion", models.CharField(max_length=400)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
