# Generated by Django 5.1 on 2024-09-02 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("facturas", "0001_initial"),
        ("productos", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="cve_cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="usuarios.cliente"
            ),
        ),
        migrations.AddField(
            model_name="factura",
            name="cve_vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="usuarios.vendedor"
            ),
        ),
        migrations.AddField(
            model_name="facturanotacredito",
            name="cve_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="productos.producto"
            ),
        ),
        migrations.AddField(
            model_name="facturanotacredito",
            name="no_factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facturas.factura"
            ),
        ),
        migrations.AddField(
            model_name="facturaproducto",
            name="cve_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="productos.producto"
            ),
        ),
        migrations.AddField(
            model_name="facturaproducto",
            name="no_factura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facturas.factura"
            ),
        ),
        migrations.AddField(
            model_name="notacredito",
            name="cve_cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="usuarios.cliente"
            ),
        ),
        migrations.AddField(
            model_name="notacredito",
            name="cve_vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="usuarios.vendedor"
            ),
        ),
        migrations.AddField(
            model_name="facturanotacredito",
            name="no_nc",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facturas.notacredito"
            ),
        ),
        migrations.AddField(
            model_name="notacreditoproducto",
            name="cve_producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="productos.producto"
            ),
        ),
        migrations.AddField(
            model_name="notacreditoproducto",
            name="no_cn",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="facturas.notacredito"
            ),
        ),
    ]
