# Generated by Django 5.1 on 2024-09-03 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturas", "0003_rename_no_cn_notacreditoproducto_no_nc"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="cve_cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="facturas_cliente",
                to="usuarios.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="cve_vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="facturas_vendedor",
                to="usuarios.vendedor",
            ),
        ),
        migrations.AlterField(
            model_name="notacredito",
            name="cve_cliente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="notas_cliente",
                to="usuarios.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="notacredito",
            name="cve_vendedor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="notas_vendedor",
                to="usuarios.vendedor",
            ),
        ),
    ]
