# Generated by Django 5.1 on 2024-09-04 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "facturas",
            "0004_alter_factura_cve_cliente_alter_factura_cve_vendedor_and_more",
        ),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pagado", "Pagado"),
                            ("pendiente", "Pendiente"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=100,
                    ),
                ),
                ("fecha_generada", models.DateTimeField()),
                (
                    "cve_ncp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="facturas.notacreditoproducto",
                    ),
                ),
                (
                    "cve_vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="usuarios.vendedor",
                    ),
                ),
            ],
        ),
    ]
